require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0.1
  Exclude:
    - '**/db/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'config.ru'
    - 'app/controllers/**/*'
    - 'app/helpers/**/*'
    - 'app/models/**/*'

Metrics:
  Enable: false

Layout/CommentIndentation:
  Enable: false

Naming/MethodName:
  Enable: false
  Include:
    - 'lib/**/*'

Style/Documentation:
  Enable: false

Bundler/OrderedGems:
  Enable: false

Style/EmptyMethod:
  Enable: false

Lint/UnusedMethodArgument:
  Enable: false